apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-credentials
  namespace: argo
  labels:
    app.kubernetes.io/name: argocd-credentials
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: argo-workflows
  annotations:
    description: ArgoCD credentials for workflow deployments
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: argocd-credentials
    creationPolicy: Owner

  data:
    - secretKey: server
      remoteRef:
        key: /idp/platform/argocd-admin
        property: server

    - secretKey: password
      remoteRef:
        key: /idp/platform/argocd-admin
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: argo
  labels:
    app.kubernetes.io/name: github-token
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: argo-workflows
  annotations:
    description: GitHub token for GitOps operations
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: github-token
    creationPolicy: Owner

  data:
    - secretKey: token
      remoteRef:
        key: /idp/platform/github-token
        property: token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cosign-kms
  namespace: argo
  labels:
    app.kubernetes.io/name: cosign-kms
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: argo-workflows
  annotations:
    description: KMS key ARN for Cosign image signing
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: cosign-kms
    creationPolicy: Owner

  data:
    - secretKey: kms_key_arn
      remoteRef:
        key: /idp/platform/cosign
        property: kms_key_arn
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-webhook
  namespace: argo
  labels:
    app.kubernetes.io/name: slack-webhook
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: argo-workflows
  annotations:
    description: Slack webhook for notifications
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: slack-webhook
    creationPolicy: Owner

  data:
    - secretKey: url
      remoteRef:
        key: /idp/platform/slack-webhook
        property: url
