apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-token
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-github-token
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: argocd-github-token
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/fast-ish
        password: "{{ .token }}"
        username: git

  data:
    - secretKey: token
      remoteRef:
        key: /idp/platform/github-token
        property: token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-admin-password
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-admin-password
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: argocd-admin-password
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: /idp/platform/argocd-admin
        property: password
