apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-cloud-credentials
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana-cloud-credentials
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: observability
  annotations:
    description: Grafana Cloud API credentials for metrics, logs, and traces
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: grafana-cloud-credentials
    creationPolicy: Owner

  data:
    - secretKey: prometheus_user
      remoteRef:
        key: /idp/platform/grafana-cloud
        property: prometheus_user

    - secretKey: loki_user
      remoteRef:
        key: /idp/platform/grafana-cloud
        property: loki_user

    - secretKey: tempo_user
      remoteRef:
        key: /idp/platform/grafana-cloud
        property: tempo_user

    - secretKey: api_key
      remoteRef:
        key: /idp/platform/grafana-cloud
        property: api_key

    - secretKey: prometheus_endpoint
      remoteRef:
        key: /idp/platform/grafana-cloud
        property: prometheus_endpoint

    - secretKey: loki_endpoint
      remoteRef:
        key: /idp/platform/grafana-cloud
        property: loki_endpoint

    - secretKey: tempo_endpoint
      remoteRef:
        key: /idp/platform/grafana-cloud
        property: tempo_endpoint
