apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-external-secrets
  annotations:
    policies.kyverno.io/title: Require External Secrets
    policies.kyverno.io/category: Secret Management
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      Prevents direct Secret creation in team namespaces.
      Secrets must be managed by External Secrets Operator.
spec:
  validationFailureAction: Audit
  background: false
  rules:
    - name: check-secret-origin
      match:
        any:
          - resources:
              kinds:
                - Secret
              namespaces:
                - "team-*"
      exclude:
        any:
          - resources:
              annotations:
                reconcile.external-secrets.io/managed: "true"
          - resources:
              name: "*-token-*"
          - resources:
              annotations:
                kubernetes.io/service-account.name: "*"
      validate:
        message: >-
          Direct Secret creation is not allowed in team namespaces.
          Use ExternalSecrets to sync secrets from AWS Secrets Manager.
        deny: {}
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-secret-data-in-env
  annotations:
    policies.kyverno.io/title: Block Hardcoded Secrets in Environment
    policies.kyverno.io/category: Secret Management
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Prevents hardcoded secrets in environment variables.
      Environment variables with sensitive names must use secretKeyRef.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-sensitive-env-vars
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - "team-*"
      validate:
        message: >-
          Environment variables with sensitive names (password, secret, token, key, api_key)
          must use secretKeyRef, not hardcoded values.
        foreach:
          - list: "request.object.spec.containers[]"
            deny:
              conditions:
                all:
                  - key: "{{ element.env[?contains(to_lower(name), 'password') || contains(to_lower(name), 'secret') || contains(to_lower(name), 'token') || contains(to_lower(name), 'api_key')] | length(@) }}"
                    operator: GreaterThan
                    value: 0
                  - key: "{{ element.env[?contains(to_lower(name), 'password') || contains(to_lower(name), 'secret') || contains(to_lower(name), 'token') || contains(to_lower(name), 'api_key')].value | length(@) }}"
                    operator: GreaterThan
                    value: 0
