apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.team.name }}-limits
  namespace: {{ .Values.team.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.team.name }}
    app.kubernetes.io/component: limit-range
    team: {{ .Values.team.name }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limitRange.default.cpu | quote }}
        memory: {{ .Values.limitRange.default.memory | quote }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequest.cpu | quote }}
        memory: {{ .Values.limitRange.defaultRequest.memory | quote }}
      max:
        cpu: {{ .Values.limitRange.max.cpu | quote }}
        memory: {{ .Values.limitRange.max.memory | quote }}
    - type: PersistentVolumeClaim
      max:
        storage: "100Gi"
      min:
        storage: "1Gi"
