# =============================================================================
# SECRET ROTATION TEMPLATE
# =============================================================================
# Template for ExternalSecret with automatic rotation support.
# Use this as a base for application secrets that need rotation.
#
# Rotation Strategy:
# - refreshInterval: How often to check for new versions
# - AWS Secrets Manager handles the actual rotation
# - Kubernetes secret is updated automatically
# =============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .name }}-secrets"
  namespace: "{{ .namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .name }}"
    app.kubernetes.io/component: external-secret
    fasti.sh/secret-rotation: enabled
  annotations:
    fasti.sh/rotation-schedule: "{{ .rotationSchedule | default \"0 0 * * 0\" }}"
    fasti.sh/last-rotation: ""
spec:
  # Refresh interval determines how quickly K8s picks up rotated secrets
  # AWS rotation happens on its own schedule
  refreshInterval: "{{ .refreshInterval | default \"1h\" }}"

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: "{{ .name }}-secrets"
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: "{{ .name }}"
          fasti.sh/managed-by: external-secrets
        annotations:
          fasti.sh/rotation-enabled: "true"

  # Data mappings from AWS Secrets Manager
  data: []  # Override per application
---
# =============================================================================
# DATABASE CREDENTIALS TEMPLATE
# =============================================================================
# Specialized template for RDS database credentials with rotation.
# AWS Secrets Manager automatically rotates RDS credentials.
# =============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .name }}-db-credentials"
  namespace: "{{ .namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .name }}"
    app.kubernetes.io/component: database-credentials
    fasti.sh/secret-rotation: enabled
spec:
  refreshInterval: 15m  # More frequent for DB creds

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: "{{ .name }}-db-credentials"
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        # Standard database connection format
        DB_HOST: "{{ `{{ .host }}` }}"
        DB_PORT: "{{ `{{ .port | default \"5432\" }}` }}"
        DB_NAME: "{{ `{{ .dbname }}` }}"
        DB_USERNAME: "{{ `{{ .username }}` }}"
        DB_PASSWORD: "{{ `{{ .password }}` }}"
        # Connection string for convenience
        DATABASE_URL: "postgresql://{{ `{{ .username }}` }}:{{ `{{ .password }}` }}@{{ `{{ .host }}` }}:{{ `{{ .port | default \"5432\" }}` }}/{{ `{{ .dbname }}` }}"

  data:
    - secretKey: host
      remoteRef:
        key: "{{ .awsSecretName }}"
        property: host
    - secretKey: port
      remoteRef:
        key: "{{ .awsSecretName }}"
        property: port
    - secretKey: dbname
      remoteRef:
        key: "{{ .awsSecretName }}"
        property: dbname
    - secretKey: username
      remoteRef:
        key: "{{ .awsSecretName }}"
        property: username
    - secretKey: password
      remoteRef:
        key: "{{ .awsSecretName }}"
        property: password
---
# =============================================================================
# API KEY TEMPLATE
# =============================================================================
# Template for API keys and tokens that need rotation
# =============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .name }}-api-keys"
  namespace: "{{ .namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .name }}"
    app.kubernetes.io/component: api-keys
    fasti.sh/secret-rotation: enabled
spec:
  refreshInterval: 30m

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: "{{ .name }}-api-keys"
    creationPolicy: Owner
    template:
      type: Opaque

  dataFrom:
    - extract:
        key: "{{ .awsSecretName }}"
