# =============================================================================
# VELERO AWS CREDENTIALS
# =============================================================================
# Uses ExternalSecrets to sync AWS credentials from Secrets Manager.
# Note: Primary authentication is via IRSA, this is for backup.
# =============================================================================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-aws-credentials
  namespace: velero
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/component: credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: velero-aws-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .access_key }}
          aws_secret_access_key={{ .secret_key }}
  data:
    - secretKey: access_key
      remoteRef:
        key: velero/aws-credentials
        property: access_key_id
    - secretKey: secret_key
      remoteRef:
        key: velero/aws-credentials
        property: secret_access_key
