apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-cost-labels
  annotations:
    policies.kyverno.io/title: Add Cost Labels from Namespace
    policies.kyverno.io/category: Cost Management
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Automatically adds cost allocation labels to pods based on namespace labels.
      This ensures all workloads are tagged for cost tracking.
spec:
  background: false
  rules:
    - name: add-team-label-from-namespace
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - "team-*"
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              +(fasti.sh/team): "{{request.namespace | replace('team-', '')}}"
              +(fasti.sh/namespace): "{{request.namespace}}"
