apiVersion: v1
kind: Namespace
metadata:
  name: kubecost
  labels:
    fasti.sh/component: cost-management
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
