apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    fasti.sh/component: observability
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
