apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-pdb-for-ha-deployments
  annotations:
    policies.kyverno.io/title: Require PodDisruptionBudget for HA Deployments
    policies.kyverno.io/category: Compliance
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/description: >-
      Deployments with multiple replicas should have a PodDisruptionBudget
      to ensure availability during voluntary disruptions like node drains.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-pdb
      match:
        any:
          - resources:
              kinds:
                - Deployment
              namespaces:
                - "team-*"
      preconditions:
        all:
          - key: "{{request.object.spec.replicas || `1`}}"
            operator: GreaterThan
            value: 1
      validate:
        message: "Deployments with >1 replica should have a PodDisruptionBudget for high availability"
        deny: {}
