apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: argocd-notifications-secret
    creationPolicy: Owner

  data:
    - secretKey: slack-token
      remoteRef:
        key: /idp/platform/slack-webhook
        property: bot_token
