apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform infrastructure applications
  sourceRepos:
    # GitOps repository - update to match your organization
    - https://github.com/fast-ish/aws-idp-gitops.git
    # Helm chart repositories
    - https://charts.jetstack.io
    - https://argoproj.github.io/argo-helm
    - https://charts.external-secrets.io
    - https://kyverno.github.io/kyverno
    - https://falcosecurity.github.io/charts
    - https://grafana.github.io/helm-charts
    - https://prometheus-community.github.io/helm-charts
    - https://kubecost.github.io/cost-analyzer
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
