apiVersion: v1
kind: Namespace
metadata:
  name: falco
  labels:
    fasti.sh/component: security
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
