# Argo Workflows database credentials
# Uses Backstage RDS with a separate database (argo_workflows)
# The Backstage RDS creates multiple databases: backstage, argo_workflows
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-workflows-db
  namespace: argo
  labels:
    app.kubernetes.io/name: argo-workflows-db
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: argo-workflows
  annotations:
    description: PostgreSQL credentials for Argo Workflows archive persistence
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: argo-workflows-db
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Argo Workflows controller expects these keys
        username: "{{ .username }}"
        password: "{{ .password }}"
        # Connection string for debugging
        host: "{{ .host }}"

  dataFrom:
    - extract:
        # Uses Backstage RDS secret - same credentials, different database
        key: oyster-backstage-db-credentials
